package ocera.rtcan.monitor;

import javax.swing.*;

/**
 * Created by IntelliJ IDEA.
 * User: fanda
 * Date: Feb 19, 2004
 * Time: 2:29:30 PM
 * To change this template use File | Settings | File Templates.
 */
public class CanMonStatusBar
{
    public JLabel lbl1;
    public JLabel lbl2;
    public JLabel lbl3;
    public JPanel panel;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$() {
        final JPanel _1;
        _1 = new JPanel();
        panel = _1;
        _1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 3, new java.awt.Insets(1, 0, 0, 0), 5, 0));
        _1.setEnabled(false);
        final JPanel _2;
        _2 = new JPanel();
        _2.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new java.awt.Insets(0, 0, 0, 0), -1, 0));
        _1.add(_2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 0, 3, 2, 0, null, null, null));
        _2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        final JLabel _3;
        _3 = new JLabel();
        lbl1 = _3;
        _3.setIconTextGap(0);
        _3.setVerticalTextPosition(1);
        _3.setVerticalAlignment(1);
        _3.setText("ahoj");
        _2.add(_3, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 8, 0, 0, 0, null, null, null));
        final JPanel _4;
        _4 = new JPanel();
        _4.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new java.awt.Insets(0, 0, 0, 0), -1, 0));
        _1.add(_4, new com.intellij.uiDesigner.core.GridConstraints(0, 1, 1, 1, 0, 3, 0, 0, null, new java.awt.Dimension(50, -1), null));
        _4.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        final JLabel _5;
        _5 = new JLabel();
        lbl2 = _5;
        _5.setIconTextGap(0);
        _5.setVerticalTextPosition(1);
        _5.setVerticalAlignment(1);
        _5.setText("lbl2");
        _4.add(_5, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 8, 0, 0, 0, null, null, null));
        final JPanel _6;
        _6 = new JPanel();
        _6.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new java.awt.Insets(0, 0, 0, 0), -1, 0));
        _1.add(_6, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, 0, 3, 0, 0, null, new java.awt.Dimension(50, -1), null));
        _6.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        final JLabel _7;
        _7 = new JLabel();
        lbl3 = _7;
        _7.setHorizontalTextPosition(2);
        _7.setIconTextGap(0);
        _7.setVerticalTextPosition(1);
        _7.setVerticalAlignment(1);
        _7.setText("lbl3");
        _6.add(_7, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, 8, 0, 0, 0, null, null, null));
    }

}
