#*******************************************************************
# The ORTCAN Project is distributed under the 
# Library Gnu General Public Licence. 
# See file COPYING for details.
#
#*******************************************************************

.PHONY: default xmlconf clean canmonitor utils-pass

all : default

utils-pass : default

.DEFAULT::
	@


default clean xmlconf canmonitor: 
	./make.ant $@



